name: Check auctions

on:
  schedule:
    - cron: "0 8 * * 1,4"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run script
      run: python licytacje.py

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465        # zmienione z 587 na 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "Raport z monitoringu licytacji"
        to: "kosciuszko.michal@gmail.com"
        from: "Bot Licytacje <kosciuszko.michal@gmail.com>"
        body: |
          Raport z działania skryptu.
          Zobacz plik log.txt w repozytorium.
      continue-on-error: true


    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: log
        path: log.txt

    - name: Commit state files
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add state_*.txt
        git commit -m "Update state files" || echo "No changes"
        git push
